### ISSUE TITLE
Good?

### ISSUE THREAD

**Issue by Vitor-Bukovitz** [GustavoMartinsDosSantos/unityGame#1]
Hello my dear friend Gustavo Martins dos Santos, I've tried your game and i'm having issued when trying to move my character. What should i do? thanks in advise

**Comment by GustavoMartinsDosSantos** [comment]
Dear Vitor, how are you?

Are you trying to play the game in desktop or mobile?

Or just cloning the project for your development?

Anyway, please, send me a few pictures from the errors, so that i can work in a solution.

Regards,
Gustavo Martins dos Santos.
47 9 97311529
________________________________

**Comment by Vitor-Bukovitz** [comment]
**useless**
